Repository moonlight-miners/Customer-Segmentation, pull requests merged in 2021-03, with the labels that each got.

#1 documentation updated.
  README.md
Labels: documentation

#3 Mind Map
  Mind-Map/CustomerSegmentation_PDF.pdf
  Mind-Map/CustomerSegmentation_SVG.svg
  Mind-Map/README.md
Labels: enhancement

#6 Mind Map re-placed into Canvases folder.
  Canvases/Mind-Map/CustomerSegmentation_PDF.pdf
  Canvases/Mind-Map/CustomerSegmentation_SVG.svg
  Canvases/Mind-Map/README.md
Labels: enhancement

#14 Uploaded Block diagram
  Literature survey and Documentation/Canvases/Block Diagram.pdf
Labels: documentation, enhancement
